#########################################################
#-------------------------------------------------------#
#                      PALABOX                          #
#-------------------------------------------------------#          
#########################################################

# MySQL - Configuration

host: 127.0.0.1
database: palabox
username: root
password: paladiumMDP123